-- ==========================================
-- CONSOLIDATED SUPABASE CLOUD MIGRATION
-- ==========================================
-- This script creates the entire database structure ON "Parser".a new Supabase instance.
-- Run this in the SQL Editor of your NEW project.

-- 1. EXTENSIONS
-- Required for UUID and random string generatiON "Parser".CREATE EXTENSION "Parser".IF NOT EXISTS "pgcrypto";
CREATE EXTENSION "Parser".IF NOT EXISTS "uuid-ossp";

-- 2. SCHEMA CREATION "Parser".CREATE SCHEMA IF NOT EXISTS "Parser";

-- 3. ENUM TYPES (If any)
-- Currently using text/jsonb for flexibility

-- 4. TABLES IN "Parser" SCHEMA

-- 4.1 Configuration & Settings
CREATE TABLE "Parser".client_configs (
    id SERIAL PRIMARY KEY,
    rest_api_key TEXT,
    kaspi_xml_url TEXT,
    kaspi_token TEXT,
    ms_login TEXT,
    ms_password TEXT,
    openai_api_key TEXT,
    retail_divisor FLOAT DEFAULT 0.3,
    min_price_divisor FLOAT DEFAULT 0.45,
    airtable_api_key TEXT,
    airtable_base_id TEXT,
    airtable_table_name TEXT,
    is_autonomous_mode BOOLEAN DEFAULT FALSE,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4.2 Core Products (Target for Conveyor)
CREATE TABLE "Parser".products (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    moysklad_id TEXT NOT NULL,
    name TEXT,
    article TEXT UNIQUE,
    code TEXT,
    price NUMERIC,
    min_price NUMERIC,
    cost_price NUMERIC,
    stock INTEGER DEFAULT 0,
    image_url TEXT,
    brand TEXT,
    rating NUMERIC,
    feedbacks INTEGER,
    specs JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4.3 WB Search Results & Conveyor Queue Task Source
CREATE TABLE "Parser".wb_search_results (
    id BIGINT PRIMARY KEY, -- WB nm_id
    positiON integer,
    name TEXT,
    brand TEXT,
    price_kzt NUMERIC,
    in_stock BOOLEAN,
    image_url TEXT,
    product_url TEXT,
    specs JSONB,
    delivery_days INTEGER,
    query TEXT,
    rating NUMERIC,
    feedbacks INTEGER,
    conveyor_status TEXT DEFAULT 'idle', -- 'idle', 'in_progress', 'completed', 'error'
    ms_created BOOLEAN DEFAULT FALSE,
    stock_added BOOLEAN DEFAULT FALSE,
    kaspi_created BOOLEAN DEFAULT FALSE,
    conveyor_log TEXT,
    airtable_id TEXT,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4.4 AutomatiON "Parser".Parser Queue
CREATE TABLE "Parser".parser_queue (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mode TEXT NOT NULL, -- 'search', 'top'
    query TEXT,
    page INTEGER DEFAULT 1,
    status TEXT DEFAULT 'pending', -- 'pending', 'processing', 'done', 'error'
    log TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4.5 Warehouse Infrastructure
CREATE TABLE "Parser".warehouses (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    moysklad_id TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4.6 Multi-Warehouse Stocks
CREATE TABLE "Parser".product_stocks (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    product_id UUID REFERENCES "Parser".products(id) ON "Parser".DELETE CASCADE,
    warehouse_id UUID REFERENCES "Parser".warehouses(id) ON "Parser".DELETE CASCADE,
    stock INTEGER DEFAULT 0,
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(product_id, warehouse_id)
);

-- 4.7 Sourcing & Price Analysis Recommendations
CREATE TABLE "Parser".sourcing_recommendations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    moysklad_id TEXT NOT NULL,
    product_name TEXT,
    image_url TEXT,
    wb_price INTEGER,
    wb_link TEXT,
    ozon_price INTEGER,
    ozon_link TEXT,
    best_price INTEGER,
    best_source TEXT,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. ACCESS PERMISSIONS (CRITICAL)
-- Grant access to the schema
GRANT USAGE ON "Parser".SCHEMA "Parser" TO anon, authenticated, service_role;

-- Grant access to all tables for commON "Parser".roles
GRANT ALL PRIVILEGES ON "Parser".ALL TABLES IN SCHEMA "Parser" TO anon, authenticated, service_role;
GRANT ALL PRIVILEGES ON "Parser".ALL SEQUENCES IN SCHEMA "Parser" TO anon, authenticated, service_role;

-- Set default privileges for future objects
ALTER DEFAULT PRIVILEGES IN SCHEMA "Parser" GRANT ALL ON "Parser".TABLES TO anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA "Parser" GRANT ALL ON "Parser".SEQUENCES TO anon, authenticated, service_role;

-- 6. SECURITY POLICIES (RLS)
ALTER TABLE "Parser".client_configs ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Parser".products ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Parser".wb_search_results ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Parser".parser_queue ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Parser".warehouses ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Parser".product_stocks ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Parser".sourcing_recommendations ENABLE ROW LEVEL SECURITY;

-- Catch-all open policies (adjust if you need tighter security later)
CREATE POLICY "Full access" ON "Parser".client_configs FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Full access" ON "Parser".products FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Full access" ON "Parser".wb_search_results FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Full access" ON "Parser".parser_queue FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Full access" ON "Parser".warehouses FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Full access" ON "Parser".product_stocks FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Full access" ON "Parser".sourcing_recommendations FOR ALL USING (true) WITH CHECK (true);

-- 7. HELPERS & UTILITIES
-- Required for some dashboard features that run dynamic SQL
CREATE OR REPLACE FUNCTION "Parser".exec_sql(sql text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  EXECUTE sql;
  RETURN '{"status": "success"}'::jsonb;
EXCEPTION "Parser".WHEN OTHERS THEN
  RETURN jsonb_build_object('status', 'error', 'message', SQLERRM);
END;
$$;
