CREATE TABLE IF NOT EXISTS "Parser".parser_queue (
    id bigint generated by default as identity primary key,
    mode text not null, -- 'search' or 'top'
    query text,
    page integer default 1,
    status text default 'pending', -- pending, processing, completed, error
    log text,
    created_at timestamp with time zone default timezone('utc'::text, now()),
    updated_at timestamp with time zone default timezone('utc'::text, now())
);

alter table "Parser".parser_queue enable row level security;
create policy "Allow all access" on "Parser".parser_queue for all using (true) with check (true);
