-- ======================================================
-- MASTER MIGRATION: FOR NEW SUPABASE ("Parser" Schema)
-- ======================================================
-- This script sets up the entire platform under the "Parser" schema.
-- Execute this once in the SQL Editor of the NEW Supabase project.

-- 1. SETUP SCHEMA
CREATE SCHEMA IF NOT EXISTS "Parser";

-- Enable necessary extensions in public (standard practice)
CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. TABLES

-- -----------------------------------------------------------------------------
-- 2.1 Configuration & Settings
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "Parser".client_configs (
    id SERIAL PRIMARY KEY,
    company_name TEXT UNIQUE DEFAULT 'VELVETO',
    rest_api_key TEXT,
    kaspi_xml_url TEXT,
    kaspi_token TEXT,
    ms_login TEXT,
    ms_password TEXT,
    openai_api_key TEXT,
    retail_divisor FLOAT DEFAULT 0.3,
    min_price_divisor FLOAT DEFAULT 0.45,
    airtable_api_key TEXT,
    airtable_base_id TEXT,
    airtable_table_name TEXT,
    is_autonomous_mode BOOLEAN DEFAULT FALSE,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Insert default config if missing
INSERT INTO "Parser".client_configs (company_name) 
VALUES ('VELVETO') 
ON CONFLICT (company_name) DO NOTHING;

-- -----------------------------------------------------------------------------
-- 2.2 Core Products (MoySklad Sync)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "Parser".products (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    moysklad_id TEXT NOT NULL UNIQUE,
    name TEXT,
    article TEXT UNIQUE,
    code TEXT,
    price NUMERIC,
    min_price NUMERIC,
    cost_price NUMERIC,
    stock INTEGER DEFAULT 0,
    image_url TEXT,
    brand TEXT,
    rating NUMERIC,
    feedbacks INTEGER,
    specs JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- -----------------------------------------------------------------------------
-- 2.3 WB Search Results & Conveyor Source
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "Parser".wb_search_results (
    id BIGINT PRIMARY KEY, -- WB nm_id
    position INTEGER,
    name TEXT,
    brand TEXT,
    price_kzt NUMERIC,
    in_stock BOOLEAN,
    image_url TEXT,
    product_url TEXT,
    specs JSONB,
    delivery_days INTEGER,
    query TEXT,
    rating NUMERIC,
    feedbacks INTEGER,
    conveyor_status TEXT DEFAULT 'idle', -- 'idle', 'processing', 'completed', 'error'
    ms_created BOOLEAN DEFAULT FALSE,
    stock_added BOOLEAN DEFAULT FALSE,
    kaspi_created BOOLEAN DEFAULT FALSE,
    conveyor_log TEXT,
    kaspi_status TEXT DEFAULT 'pending', -- 'pending', 'moderation', 'approved', 'rejected'
    kaspi_details TEXT,
    kaspi_upload_id TEXT,
    airtable_id TEXT,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- -----------------------------------------------------------------------------
-- 2.4 Automation Parser Queue
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "Parser".parser_queue (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mode TEXT NOT NULL, -- 'search', 'top'
    query TEXT,
    page INTEGER DEFAULT 1,
    status TEXT DEFAULT 'pending', -- 'pending', 'processing', 'completed', 'error'
    log TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- -----------------------------------------------------------------------------
-- 2.5 Warehouse Infrastructure & Multi-Warehouse Stocks
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "Parser".warehouses (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    moysklad_id TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "Parser".product_stocks (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    product_id UUID REFERENCES "Parser".products(id) ON DELETE CASCADE,
    warehouse_id UUID REFERENCES "Parser".warehouses(id) ON DELETE CASCADE,
    stock INTEGER DEFAULT 0,
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(product_id, warehouse_id)
);

-- -----------------------------------------------------------------------------
-- 2.6 Sourcing & Price Analysis Recommendations
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "Parser".sourcing_recommendations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    moysklad_id TEXT NOT NULL,
    product_name TEXT,
    image_url TEXT,
    wb_price INTEGER,
    wb_link TEXT,
    ozon_price INTEGER,
    ozon_link TEXT,
    best_price INTEGER,
    best_source TEXT,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. PERMISSIONS
-- Grant access to the schema
GRANT USAGE ON SCHEMA "Parser" TO anon, authenticated, service_role;

-- Grant access to all existing and future tables/sequences
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA "Parser" TO anon, authenticated, service_role;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA "Parser" TO anon, authenticated, service_role;

ALTER DEFAULT PRIVILEGES IN SCHEMA "Parser" GRANT ALL ON TABLES TO anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA "Parser" GRANT ALL ON SEQUENCES TO anon, authenticated, service_role;

-- 4. ROW LEVEL SECURITY (RLS)
-- Enable RLS on all tables
DO $$ 
DECLARE
    r RECORD;
BEGIN
    FOR r IN (SELECT tablename FROM pg_tables WHERE schemaname = 'Parser') LOOP
        EXECUTE 'ALTER TABLE "Parser"."' || r.tablename || '" ENABLE ROW LEVEL SECURITY';
    END LOOP;
END $$;

-- Policies: For simplicity, we grant "Full access" for now. 
-- In a multi-tenant environment, these would be restricted by user_id or similar.
DO $$ 
DECLARE
    r RECORD;
BEGIN
    FOR r IN (SELECT tablename FROM pg_tables WHERE schemaname = 'Parser') LOOP
        EXECUTE 'CREATE POLICY "Full access" ON "Parser"."' || r.tablename || '" FOR ALL USING (true) WITH CHECK (true)';
    EXCEPTION WHEN duplicate_object THEN
        -- Skip if policy already exists
        NULL;
    END LOOP;
END $$;

-- 5. HELPER FUNCTIONS
-- exec_sql: Used for running dynamic SQL from the dashboard (if required)
CREATE OR REPLACE FUNCTION "Parser".exec_sql(sql text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  EXECUTE sql;
  RETURN '{"status": "success"}'::jsonb;
EXCEPTION WHEN OTHERS THEN
  RETURN jsonb_build_object('status', 'error', 'message', SQLERRM);
END;
$$;
